services:
  github-runner-linux-x64:
    image: github-runner:latest
    stdin_open: true
    tty: true
    build:
      context: .
    platform: linux/amd64
    environment:
      REPO: 
      TOKEN:
      RUNNER_NAME: 'linux-x64'
      RUNNER_WORKDIR: '/home/docker/_work'
      RUNNER_LABELS: kondrat,ubuntu,20.04,x64
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M